/**
 * ============================================================================
 * PHASE 1: CEO AGENT TYPES
 * ============================================================================
 */

export interface BusinessGoal {
  goal: string;       // e.g., "Build a minimum viable food delivery app"
  timeframe: string;  // e.g., "Q1", "Months 1-3"
  metric: string;     // e.g., "100 active beta testers"
}

export interface SuggestedDepartment {
  name: string;       // e.g., "Product & Engineering", "Marketing"
  purpose: string;    // The core reason this department exists
  focus: string;      // The primary focus area for the first 90 days (e.g., "Build core MVP features")
}

export interface MilestonePhase {
  title: string;
  milestones: string[];
}

export interface CEOOutput {
  companyName: string;                     // The AI-generated name for the startup
  vision: string;                          // Long-term aspiration of the company
  mission: string;                         // Present focus and core purpose
  businessGoals: BusinessGoal[];           // Key milestones with timeframes and metrics
  suggestedDepartments: SuggestedDepartment[]; // Initial organizational structure
  first90DayPlan: {
    days30: MilestonePhase;                // Month 1 roadmap
    days60: MilestonePhase;                // Month 2 roadmap
    days90: MilestonePhase;                // Month 3 roadmap
  };
}

/**
 * ============================================================================
 * PHASE 2: RESEARCH AGENT TYPES
 * ============================================================================
 */

export interface Competitor {
  name: string;
  description: string;
  strengths: string[];
  weaknesses: string[];
}

export interface MarketOpportunity {
  opportunity: string;
  potentialImpact: string; // e.g., "High", "Medium", "Low"
}

export interface IndustryTrend {
  trend: string;
  relevance: string; // Explanation of how it impacts the startup
}

export interface BusinessRisk {
  risk: string;
  severity: string; // e.g., "High", "Medium", "Low"
  mitigation: string; // Mitigation strategy
}

export interface TargetAudience {
  demographics: string; // e.g., "Age 18-35 tech professionals"
  painPoints: string[]; // List of core problems they face
  whyTheyBuy: string;   // Core value proposition that appeals to them
}

export interface ResearchOutput {
  competitors: Competitor[];
  marketOpportunities: MarketOpportunity[];
  industryTrends: IndustryTrend[];
  risks: BusinessRisk[];
  targetAudience: TargetAudience;
}

/**
 * ============================================================================
 * PHASE 3: PRODUCT MANAGER AGENT TYPES
 * ============================================================================
 */

export interface UserPersona {
  name: string;          // e.g., "Busy Parent Sarah"
  role: string;          // Occupation or life stage (e.g., "Working Mother")
  goals: string[];       // Goals Sarah has related to this product category
  painPoints: string[];  // Sarah's current struggles or blockers
}

export interface MVPFeature {
  name: string;          // e.g., "Instant salad recommendation wizard"
  description: string;   // What the feature does
  value: string;         // The business or user value of this feature
}

export interface FeaturePriority {
  tier: string;          // e.g., "Must Have (MVP)", "Should Have (Post-MVP)", "Could Have (Nice-to-Have)"
  features: string[];    // Names of the features belonging to this tier
}

export interface ProductRoadmapPhase {
  phaseName: string;     // e.g., "v1.0 (MVP Launch)"
  timeline: string;      // e.g., "Months 1-2"
  keyDeliverables: string[]; // List of concrete milestones or features delivered in this phase
}

/**
 * The structured output generated by the Product Agent.
 */
export interface ProductOutput {
  usp: string;                          // Unique Selling Proposition (why this product wins)
  userPersonas: UserPersona[];          // The key user archetypes this product solves problems for
  mvpFeatures: MVPFeature[];            // Core feature set scoping
  featurePriorities: FeaturePriority[];  // Priority matrix (Must/Should/Could)
  productRoadmap: {
    phase1: ProductRoadmapPhase;        // Launch scope
    phase2: ProductRoadmapPhase;        // Optimization scope
    phase3: ProductRoadmapPhase;        // Scale scope
  };
}

/**
 * Combined response payload containing CEO, Research, and Product analyses.
 * 
 * FUTURE SCALABILITY:
 * When adding Finance and Investor agents later, we can expand this response by adding:
 * - `finance?: FinanceOutput;`
 * - `investor?: InvestorOutput;`
 * 
 * Keeping this structure flat and modular allows agents to read inputs cleanly.
 */
export interface Phase3Output {
  ceo: CEOOutput;
  research: ResearchOutput;
  product: ProductOutput;
}
