/**
 * Represents a specific business goal for the startup.
 * A structured goal includes the timeframe and metric for tracking success.
 */
export interface BusinessGoal {
  goal: string;       // e.g., "Build a minimum viable food delivery app"
  timeframe: string;  // e.g., "Q1", "Months 1-3"
  metric: string;     // e.g., "100 active beta testers"
}

/**
 * Represents a department recommended by the CEO for the startup's operational success.
 */
export interface SuggestedDepartment {
  name: string;       // e.g., "Product & Engineering", "Marketing"
  purpose: string;    // The core reason this department exists
  focus: string;      // The primary focus area for the first 90 days (e.g., "Build core MVP features")
}

/**
 * Represents a milestone phase for the 90-day plan.
 * Each phase has a title (e.g., "Days 1-30: Foundation & Design") and a list of key milestones.
 */
export interface MilestonePhase {
  title: string;
  milestones: string[];
}

/**
 * The structured plan generated by the CEO Agent.
 * This object is strictly populated by the Gemini API structured JSON output.
 */
export interface CEOOutput {
  companyName: string;                     // The AI-generated name for the startup
  vision: string;                          // Long-term aspiration of the company
  mission: string;                         // Present focus and core purpose
  businessGoals: BusinessGoal[];           // Key milestones with timeframes and metrics
  suggestedDepartments: SuggestedDepartment[]; // Initial organizational structure
  first90DayPlan: {
    days30: MilestonePhase;                // Month 1 roadmap
    days60: MilestonePhase;                // Month 2 roadmap
    days90: MilestonePhase;                // Month 3 roadmap
  };
}
