import { aiClient } from "../lib/gemini";
import { CEOOutput, ResearchOutput } from "../types";

/**
 * ResearchAgent Class
 * 
 * AGENT ROLE:
 * This agent acts as the Lead Market Researcher. Unlike the CEO who focuses on the high-level
 * company structure and core values, the Research Agent is dedicated to market validation:
 * - Analyzing the competitive landscape (competitors' strengths/weaknesses).
 * - Identifying market opportunities and gaps.
 * - Tracking current and future industry trends.
 * - Outlining major risks (and how to mitigate them).
 * - Defining the exact target audience, their pain points, and buyer motivation.
 * 
 * AGENT COMMUNICATION & DATA FLOW DESIGN:
 * In a multi-agent system, agents need context from other agents to maintain alignment. 
 * Here, we use Dependency Injection: the output of the CEOAgent is passed directly into
 * the ResearchAgent. This simulates a "Chief of Staff" or "CEO brief" where the researcher
 * studies the CEO's directive before compiling their report.
 * 
 * SCALABILITY DESIGN (Future Proofing):
 * This sequential, decoupled structure is highly modular. When we eventually add the
 * Product Manager, Finance, and Investor agents:
 * 1. The Product Manager Agent can read both the CEO plan AND the Research market insights to write product requirements (PRD).
 * 2. The Finance Agent can use the CEO's departments and the Product/Research milestones to build a cash flow forecast.
 * 3. The Investor Agent can evaluate the combined outputs of all agents to write a pitch score.
 * This is all achieved without complex framework overhead (like LangGraph), keeping the code easy to understand.
 */
export class ResearchAgent {
  private modelName: string;

  constructor() {
    this.modelName = process.env.GEMINI_MODEL || "gemini-2.5-flash";
  }

  /**
   * Generates a structured market analysis based on the startup idea and CEO's vision.
   * 
   * @param startupIdea - The raw business idea entered by the user.
   * @param ceoOutput - The output generated by the CEO Agent in Step 1.
   * @returns A promise that resolves to the structured ResearchOutput.
   */
  async generateResearch(startupIdea: string, ceoOutput: CEOOutput): Promise<ResearchOutput> {
    if (!startupIdea || startupIdea.trim() === "") {
      throw new Error("Startup idea cannot be empty");
    }

    if (!ceoOutput || !ceoOutput.companyName) {
      throw new Error("CEO strategic context is missing or invalid");
    }

    // Persona instruction: Sets the domain-expert mindset for the LLM.
    const systemInstruction = `
      You are the Lead Market Researcher of a newly founded startup.
      Your job is to analyze the market opportunity, identify key competitors, and assess potential risks.
      You must read the CEO's high-level company plan, vision, and organizational departments to align
      your research with the CEO's strategic direction.
      Be realistic, analytical, and specific. Provide actual industry insights instead of generic advice.
    `;

    // Data-injection prompt: This is how the CEO Output flows to the Research Agent.
    // We serialize the CEO's output so the model can inspect the company name, vision, mission, and departments.
    const prompt = `
      Perform a deep-dive market research and analysis for the following startup idea and CEO strategic plan.

      --- STARTUP IDEA ---
      "${startupIdea}"

      --- CEO STRATEGIC PLAN ---
      Company Name: ${ceoOutput.companyName}
      Vision: ${ceoOutput.vision}
      Mission: ${ceoOutput.mission}
      Goals: ${JSON.stringify(ceoOutput.businessGoals)}
      Suggested Departments: ${JSON.stringify(ceoOutput.suggestedDepartments)}

      --- INSTRUCTIONS ---
      Analyze the specific target audience, competitors (along with their strengths/weaknesses),
      unexplored market opportunities, current industry trends, and business risks.
      Ensure the analysis is highly relevant to ${ceoOutput.companyName}'s vision and mission.
    `;

    // Strict OpenAPI 3.0 schema matching the ResearchOutput interface.
    const responseSchema = {
      type: "OBJECT",
      properties: {
        competitors: {
          type: "ARRAY",
          description: "List 2 to 3 key competitors (direct or indirect) in this market space.",
          items: {
            type: "OBJECT",
            properties: {
              name: { type: "STRING", description: "Name of the competitor." },
              description: { type: "STRING", description: "What services/products they offer." },
              strengths: { 
                type: "ARRAY", 
                items: { type: "STRING" },
                description: "List of key advantages this competitor possesses." 
              },
              weaknesses: { 
                type: "ARRAY", 
                items: { type: "STRING" },
                description: "List of key vulnerabilities or gaps in their offering."
              }
            },
            required: ["name", "description", "strengths", "weaknesses"]
          }
        },
        marketOpportunities: {
          type: "ARRAY",
          description: "List 2 to 3 market opportunities or underserved niches this company can leverage.",
          items: {
            type: "OBJECT",
            properties: {
              opportunity: { type: "STRING", description: "Description of the market gap/opportunity." },
              potentialImpact: { type: "STRING", description: "Expected impact on the business: High, Medium, or Low." }
            },
            required: ["opportunity", "potentialImpact"]
          }
        },
        industryTrends: {
          type: "ARRAY",
          description: "Key technological, economic, or behavioral trends relevant to this industry.",
          items: {
            type: "OBJECT",
            properties: {
              trend: { type: "STRING", description: "Description of the industry trend." },
              relevance: { type: "STRING", description: "How this trend affects the startup's roadmap." }
            },
            required: ["trend", "relevance"]
          }
        },
        risks: {
          type: "ARRAY",
          description: "Key risks (market, technical, execution) and mitigation strategies.",
          items: {
            type: "OBJECT",
            properties: {
              risk: { type: "STRING", description: "Description of the threat or risk." },
              severity: { type: "STRING", description: "Severity of the risk: High, Medium, or Low." },
              mitigation: { type: "STRING", description: "Clear mitigation plan to reduce this risk." }
            },
            required: ["risk", "severity", "mitigation"]
          }
        },
        targetAudience: {
          type: "OBJECT",
          description: "Detailed description of the primary customer profile.",
          properties: {
            demographics: { type: "STRING", description: "Demographic profile of the target users (e.g., small business owners, gen-z gamers)." },
            painPoints: { 
              type: "ARRAY", 
              items: { type: "STRING" },
              description: "The primary frustrations or problems they currently experience." 
            },
            whyTheyBuy: { type: "STRING", description: "The core value proposition driving them to purchase this solution." }
          },
          required: ["demographics", "painPoints", "whyTheyBuy"]
        }
      },
      required: [
        "competitors",
        "marketOpportunities",
        "industryTrends",
        "risks",
        "targetAudience"
      ]
    };

    try {
      // Execute the request to the Gemini API using the singleton client
      const response = await aiClient.models.generateContent({
        model: this.modelName,
        contents: prompt,
        config: {
          systemInstruction,
          responseMimeType: "application/json",
          responseSchema: responseSchema as any,
        },
      });

      const responseText = response.text;
      
      if (!responseText) {
        throw new Error("No response received from the Gemini API during research generation");
      }

      // Parse output into the expected ResearchOutput structure
      const parsedData = JSON.parse(responseText) as ResearchOutput;
      return parsedData;

    } catch (error) {
      console.error("ResearchAgent execution failed:", error);
      throw error;
    }
  }
}
