import { aiClient } from "../lib/gemini";
import { 
  CEOOutput, 
  ResearchOutput, 
  ProductOutput, 
  FinanceOutput, 
  InvestorOutput, 
  SummaryOutput 
} from "../types";

/**
 * SummaryAgent Class
 * 
 * AGENT ROLE:
 * This agent acts as the Chief of Staff or Investment Committee Secretary.
 * Unlike standard vertical agents, the Summary Agent is a horizontal synthesizer:
 * - It reads all previous outputs: CEO, Research, PM, CFO, and Investor.
 * - It compiles a high-level strategic brief (Executive Summary).
 * - It calculates consolidated startup, confidence, and readiness scores.
 * - It selects exactly 3 key strengths, 3 key weaknesses, 3 immediate 30-day actions,
 *   and 3 medium-term 90-day actions.
 * - It delivers a final verdict on incubator viability.
 * 
 * MODULARITY & FUTURE PDF EXPORTS:
 * By centralizing the summary analysis in a clean structured JSON schema, this agent
 * is highly reusable. Downstream services can export this output directly to standard
 * templates (like a markdown pitch deck, executive PDF, or email brief) without
 * calling any LLMs or parsing complex logs.
 */
export class SummaryAgent {
  private modelName: string;

  constructor() {
    this.modelName = process.env.GEMINI_MODEL || "gemini-2.5-flash";
  }

  /**
   * Synthesizes all preceding agent outputs into a unified summary report.
   */
  async generateExecutiveSummary(
    startupIdea: string,
    ceoOutput: CEOOutput,
    researchOutput: ResearchOutput,
    productOutput: ProductOutput,
    financeOutput: FinanceOutput,
    investorOutput: InvestorOutput
  ): Promise<SummaryOutput> {
    if (!startupIdea || startupIdea.trim() === "") {
      throw new Error("Startup idea cannot be empty");
    }

    if (!ceoOutput || !ceoOutput.companyName) {
      throw new Error("CEO context is missing or invalid");
    }

    if (!researchOutput || !researchOutput.targetAudience) {
      throw new Error("Research context is missing or invalid");
    }

    if (!productOutput || !productOutput.usp) {
      throw new Error("Product context is missing or invalid");
    }

    if (!financeOutput || !financeOutput.fundingRequirement) {
      throw new Error("Finance context is missing or invalid");
    }

    if (!investorOutput || !investorOutput.recommendation) {
      throw new Error("Investor context is missing or invalid");
    }

    const systemInstruction = `
      You are the Chief of Staff of a startup incubator.
      Your job is to read all preceding documents generated by the CEO, Market Researcher, PM, CFO, and VC agents
      and compile a final strategic Executive Summary report.
      Be concise, strategic, and balanced. Avoid fluff. Provide exact ratings and action items.
    `;

    // Prompt injecting all previous outputs
    const prompt = `
      Synthesize all preceding strategic, product, financial, and VC documents for:

      --- RAW IDEA ---
      "${startupIdea}"

      --- CEO STRATEGY ---
      Company Name: ${ceoOutput.companyName}
      Vision: ${ceoOutput.vision}
      Mission: ${ceoOutput.mission}
      Goals: ${JSON.stringify(ceoOutput.businessGoals)}

      --- MARKET RESEARCH ---
      Competitors: ${JSON.stringify(researchOutput.competitors)}
      Gaps/Opportunities: ${JSON.stringify(researchOutput.marketOpportunities)}
      Target Audience: ${JSON.stringify(researchOutput.targetAudience)}

      --- PRODUCT STRATEGY ---
      USP: ${productOutput.usp}
      MVP Features: ${JSON.stringify(productOutput.mvpFeatures)}
      Roadmap: ${JSON.stringify(productOutput.productRoadmap)}

      --- FINANCIAL STRATEGY ---
      Funding Target: ${financeOutput.fundingRequirement}
      OPEX & Costs: ${JSON.stringify(financeOutput.monthlyOperatingExpenses)}
      Monetization: ${JSON.stringify(financeOutput.revenueStreams)}

      --- VC CRITIQUE ---
      Verdict: ${investorOutput.recommendation}
      Score: ${investorOutput.investmentScore}/10
      Strengths/Weaknesses: ${JSON.stringify(investorOutput.strengths)} / ${JSON.stringify(investorOutput.weaknesses)}

      --- INSTRUCTIONS ---
      Produce a final Executive Summary brief.
      Generate:
      1. An executive summary paragraph.
      2. Consolidated Startup Score (0.0 - 10.0).
      3. Confidence Score (0 - 100).
      4. Startup Readiness Score (0 - 100).
      5. Top 2-3 opportunities and risks.
      6. Exactly 3 strengths and exactly 3 weaknesses.
      7. Exactly 3 immediate actions (next 30 days) and exactly 3 medium-term actions (next 90 days).
      8. Final verdict string.
    `;

    // Strict OpenAPI 3.0 response schema matching SummaryOutput
    const responseSchema = {
      type: "OBJECT",
      properties: {
        executiveSummary: {
          type: "STRING",
          description: "Narrative briefing summarizing company, product scope, financial viability, and target markets."
        },
        startupScore: {
          type: "NUMBER",
          description: "Incubator startup rating from 0.0 to 10.0 based on feasibility and VC critique."
        },
        confidenceScore: {
          type: "INTEGER",
          description: "Incubator confidence rating from 0 to 100 based on data alignment."
        },
        startupReadinessScore: {
          type: "INTEGER",
          description: "Incubator readiness rating from 0 to 100 measuring launch feasibility."
        },
        topOpportunities: {
          type: "ARRAY",
          description: "Top 2-3 consolidated opportunities.",
          items: { type: "STRING" }
        },
        topRisks: {
          type: "ARRAY",
          description: "Top 2-3 consolidated threat vectors.",
          items: { type: "STRING" }
        },
        topStrengths: {
          type: "ARRAY",
          description: "Provide exactly 3 synthesized strengths.",
          items: { type: "STRING" }
        },
        topWeaknesses: {
          type: "ARRAY",
          description: "Provide exactly 3 synthesized weaknesses.",
          items: { type: "STRING" }
        },
        immediateActions: {
          type: "ARRAY",
          description: "Exactly 3 actionable next steps to complete in the next 30 days.",
          items: { type: "STRING" }
        },
        mediumTermActions: {
          type: "ARRAY",
          description: "Exactly 3 actionable next steps to complete in the next 90 days.",
          items: { type: "STRING" }
        },
        finalVerdict: {
          type: "STRING",
          description: "Final incubator verdict (e.g., 'Ready for Launch', 'Needs Financial Modeling', 'High Risk - Pivot Required')."
        }
      },
      required: [
        "executiveSummary",
        "startupScore",
        "confidenceScore",
        "startupReadinessScore",
        "topOpportunities",
        "topRisks",
        "topStrengths",
        "topWeaknesses",
        "immediateActions",
        "mediumTermActions",
        "finalVerdict"
      ]
    };

    try {
      const response = await aiClient.models.generateContent({
        model: this.modelName,
        contents: prompt,
        config: {
          systemInstruction,
          responseMimeType: "application/json",
          responseSchema: responseSchema as any,
        },
      });

      const responseText = response.text;
      
      if (!responseText) {
        throw new Error("No response received from the Gemini API during summary generation");
      }

      const parsedData = JSON.parse(responseText) as SummaryOutput;
      return parsedData;

    } catch (error) {
      console.error("SummaryAgent execution failed:", error);
      throw error;
    }
  }
}
export default SummaryAgent;
